# Generated by Django 2.2.7 on 2019-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sourcecode',
            field=models.URLField(default=None),
        ),
    ]
