# Generated by Django 2.2.3 on 2019-09-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Index',
        ),
    ]
